const data = [
  {
    productID: 1,
    reviewHeading: 'review heading #1',
    reviewText: "this product is awesome",
    reviewUsername: 'TedCruzForHumanPresident',
    reviewRating: 5,
    reviewRecommended: true,
    reviewHelpful: 10,
    reviewUnhlpful: 5,
    reviewQuality: 5,
    reviewValue: 5,
    reviewEaseOfUse: 5,
    reviewImages: [],
    createdAt: 12/12/1923
  },
  {
    productID: 1,
    reviewHeading: 'BAD BAD NOT GOOD',
    reviewText: "This product is the worst",
    reviewUsername: 'MitthewRomney',
    reviewRating: 1,
    reviewRecommended: false,
    reviewHelpful: 1,
    reviewUnhelpful: 10,
    reviewQuality: 2,
    reviewValue: 3,
    reviewEaseOfUse: 1,
    reviewImages: [],
    createdAt: 12/19/1854
  },
  {
    productID: 1,
    reviewHeading: 'AAAHH',
    reviewText: "I don't like this very much",
    reviewUsername: 'BananaPhone2',
    reviewRating: 2,
    reviewRecommended: false,
    reviewHelpful: 10,
    reviewUnhelpful: 0,
    rereviewQualitylity: 2,
    reviewValue: 4,
    reviewEaseOfUse: 3,
    reviewImages: [],
    createdAt: 08/07/2020
  },
  {
    productID: 4,
    reviewHeading: 'Pon de replay',
    reviewText: "This thing changed my life!",
    reviewUsername: 'Riri4me',
    reviewRating: 5,
    reviewRecommended: true,
    reviewHelpful: 10,
    reviewUnhelpful: 10,
    reviewQuality: 5,
    reviewValue: 5,
    reviewEaseOfUse: 5,
    reviewImages: [],
    createdAt: 10/10/2010
  },
  {
    productID: 4,
    reviewHeading: 'Off with the plank',
    reviewText: "Yarg, a pirate's life for me",
    reviewUsername: 'PirateSteve',
    reviewRating: 4,
    reviewRecommended: true,
    reviewHelpful: 0,
    reviewUnhelpful: 20,
    reviewQuality: 4,
    reviewValue: 5,
    reviewEaseOfUse: 3,
    reviewImages: ['https://bloximages.chicago2.vip.townnews.com/napavalleyregister.com/content/tncms/assets/v3/editorial/d/b8/db84f292-5e7f-11e5-98bb-fbdc466793df/55fcdb5212153.image.jpg?crop=600%2C338%2C0%2C21&resize=600%2C338&order=crop%2Cresize', 'https://lh3.googleusercontent.com/proxy/CVoOExjNPfC8yxIaSFd_MwcQayNpGdoBgcEypNOovknrwRozy2SsIPThNdzsCnnrlpgsyLyBaSLjcdpvRKWHL7IEPaAwbIeXUJtlpeJZd2vyGraNG5KNI19QWyxJU6LINFkMZWS-08RYgp6hZXoPODfrmUUSjEr9MkW1ASi0HjidZCUH-lQRMI5752RfoXgDdPSnMjjwagCNnn-ozZDX4dzT-SoG'],
    createdAt: 06/10/1976
  },
  {
    productID: 6,
    reviewHeading: 'He was a big ol wimp!',
    reviewText: "I beat someone up for this product on Black Friday. Totally worth it!",
    reviewUsername: 'TykeMyson',
    reviewRating: 5,
    reviewRecommended: true,
    reviewHelpful: 4,
    reviewUnhelpful: 9,
    reviewQuality: 5,
    reviewValue: 4,
    reviewEaseOfUse: 3,
    reviewImages: [],
    createdAt: 11/29/2011
  },
  {
    productID: 6,
    reviewHeading: 'Ouch!',
    reviewText: "I got beat up while trying to get this product on Black Friday. I'll see you in court Best Buy",
    reviewUsername: 'EvandersEar',
    reviewRating: 0,
    reviewRecommended: false,
    reviewHelpful: 0,
    reviewUnhelpful: 0,
    reviewQuality: 1,
    reviewValue: 1,
    reviewEaseOfUse: 1,
    reviewImages: [],
    createdAt: 11/29/2011
  },
  {
    productID: 8,
    reviewHeading: 'CheapCheapCheap!',
    reviewText: "I got this new iPhone 11 for $2000 for my 2 year old. She is going to love it!",
    reviewUsername: 'Tim',
    reviewRating: 2,
    reviewRecommended: true,
    reviewHelpful: 100,
    reviewUnhelpful: 1000,
    reviewQuality: 3,
    reviewValue: 4,
    reviewEaseOfUse: 5,
    reviewImages: [],
    createdAt: 11/20/2000
  },
  {
    productID: 9,
    reviewHeading: 'heh',
    reviewText: "More like worst buy, if you ask me",
    reviewUsername: 'abc123',
    reviewRating: 0,
    reviewRecommended: false,
    reviewHelpful: 1,
    reviewUnhelpful: 2,
    reviewQuality: 1,
    reviewValue: 1,
    reviewEaseOfUse: 1,
    reviewImages: [],
    createdAt: 11/12/2006
  },
  {
    productID: 10,
    reviewHeading: '1 <3 Mark',
    reviewText: "Shout out to your employee Mark - the Best Guy at Best Buy",
    reviewUsername: 'MarkFrmBestBuy',
    reviewRating: 4,
    reviewRecommended: true,
    reviewHelpful: 1,
    reviewUnhelpful: 100,
    reviewQuality: 4,
    reviewValue: 3,
    reviewEaseOfUse: 5,
    reviewImages: [],
    createdAt: 09/04/2018
  }
]

module.exports.data = data;